---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
   Private nested stack CloudFormation template. This is included in the 
   root cape-infra.yml root stack. 
   This template and other nested sub-stack templates are used to deploy an 
   example architecture to get some experience with these things under our 
   belts. In all templates, things we do not know yet that need to be filled in
   eventually are noted with `[TBD]`. Items that are commented out are either 
   not known or not needed. These will be cleaned up as we go.

#Metadata:
   # [TBD] 
 
#Parameters:
   # [TBD] 

#Rules:
   # [TBD] 

#Mappings:
   # [TBD] 

#Conditions:
   # [TBD] 

#Transform:
   # [TBD] 

Resources:
  CAPEBSPrivateIAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Capabilities:
        # this stack creates a protected named user and this capability is 
        # required
        - CAPABILITY_NAMED_IAM
      #ChangeSetId: String
      #CreationTime: String
      DependsOn:
        - CAPEBSPrivateDLHStack
      Description: >
        The private IAM nested stack. Creates IAM users, roles, etc.
      #DisableRollback: Boolean
      EnableTerminationProtection: True
      #LastUpdateTime: String
      #NotificationARNs: 
      #  - String
      #Outputs: 
      #  - Output
      #Parameters: 
      #  Key: [TBD]
      #ParentId: String
      #RoleARN: [TBD]
      #RootId: String
      #StackId: String
      StackName: "cape-babysteps-private-iam-stack"
      #StackPolicyBody: Json
      #StackPolicyURL: String
      #StackStatus: String
      #StackStatusReason: String
      #Tags: 
      #  - [TBD]
      #TemplateBody: Json
      TemplateURL: plumbing/iam.yml
      #TimeoutInMinutes: Integer

  CAPEBSPrivateDLHStack:
    Type: AWS::CloudFormation::Stack
    Properties:
        #Capabilities:
      #ChangeSetId: String
      #CreationTime: String
      Description: >
        The private data lake house nested stack. Creates S3 buckets and 
        transforms.
      #DisableRollback: Boolean
      EnableTerminationProtection: True
      #LastUpdateTime: String
      #NotificationARNs: 
      #  - String
      #Outputs: 
      #  - Output
      #Parameters: 
      #  Key: [TBD]
      #ParentId: String
      #RoleARN: [TBD]
      #RootId: String
      #StackId: String
      StackName: "cape-babysteps-private-dlh-stack"
      #StackPolicyBody: Json
      #StackPolicyURL: String
      #StackStatus: String
      #StackStatusReason: String
      #Tags: 
      #  - [TBD]
      #TemplateBody: Json
      TemplateURL: plumbing/data-lake-house.yml
      #TimeoutInMinutes: Integer

  CAPEBSPrivateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/24"
      EnableDnsHostnames: True
      EnableDnsSupport: True
      #InstanceTenancy: String
      #Ipv4IpamPoolId: String
      #Ipv4NetmaskLength: Integer
      #Tags: 
      #  - [TBD]

#Outputs:
   # [TBD] 
